### ISSUE TITLE
Thiết kế cơ sở dữ liệu

### ISSUE THREAD

**Issue by NguyenThanhChung147** [CNPMGroup12-2017/CNPM#16]
Việt Trần phụ trách chính.
Mọi người thảo luận về CSDL tại đây.

**Comment by doainguyen1997** [comment]
Việt tạo thêm cho t 3 bảng dữ liệu nữa về VIỆC_LÀM (lấy ra danh sách các việc làm, vd : bất động sản, cntt, dệt may,...), MỨC_LƯƠNG (lấy ds các mốc lương cơ bản, vd : <3tr, 3-5tr,...,>20tr,..), KHU_VỰC ( lấy ds các khu vực chính, hoặc có thể 63 tỉnh thành, hoặc chỉ các thành phố lớn,...) để t cho select trong phần tìm kiếm việc làm
