### ISSUE TITLE
Phần Mềm Quản Lý Mã Nguồn Rời Rạc

### ISSUE THREAD

**Issue by NguyenThanhChung147** [CNPMGroup12-2017/CNPM#2]
Là học sinh sinh viên ngành CNTT không ít người bị reset mất hết code học tập cũ. Phần mềm giải quyết vấn đề này bằng cách đưa lên server(có thể của google) để tránh mất mát sau mỗi lần tải lên và được mã hóa cẩn thận

**Comment by NguyenThanhChung147** [comment]
Cái này đơn giản hơn mọi người có thể thảo luận.

**Comment by doainguyen1997** [comment]
Mình thấy cái này hơi mơ hồ và khó hình dung xem phải làm thế nào, và đã có phần mềm để quản lái source code trên web rồi mà.

**Comment by NguyenThanhChung147** [comment]
cái này là t nghĩ nên để tự động up lên và share code cho mọi người nữa thì tốt

**Comment by doainguyen1997** [comment]
Các doanh nghiệp CNTT hiện nay đều có phần mềm quản lí code cho mỗi dự án, chỉ chia sẻ cho nhân viên tham gia dự án ấy thôi, share code cho mọi người xem thì chết giở
