### ISSUE TITLE
Phần Mềm Đặt Đồ Ăn Qua Mạng Và Quảng Cáo Liên Kết Nhà Hàng

### ISSUE THREAD

**Issue by NguyenThanhChung147** [CNPMGroup12-2017/CNPM#3]
Với xu hướng phát triển hiện tại ở các thành phố lớn số người di cư đến các trung tâm lớn là rất nhiều trong đó có các công nhân, nhân viên và sinh viên với số lượng lớn. Để đáp ứng nhu cầu ăn uống của họ nhiều quán ăn bình dân mọc lên khắp nơi tuy nhiên không phải ai cũng biết đến một quán ăn mới. Những quán ăn mới thường cạnh tranh nhau về khách hàng có những trương trình quảng cáo trong thời gian ngắn hạn mà chưa có liên kết với nhau, vì vậy yêu cầu đặt ra là áp dụng CNTT vào quảng bá và tạo liên kết giữa các nhà hàng nhỏ lẻ này.

**Comment by NguyenThanhChung147** [comment]
Y/C phần mềm đáp ứng được thị hiếu cũng như đảm bảo chất lượng đồ ăn bên phía nhà hàng phải có những tính năng như bảng giá từng phần ăn, những xuất ăn khuyến nghị cho một số cá nhân cụ thể như bệnh nhân, thời gian và địa điểm của người đặt hàng để tìm nhà hàng gần đó nhất, chương trình quảng cáo phù hợp(tùy vào số nhà hàng liên kết và kinh phí cho quảng cáo của họ), phiếu khảo sát định kì, lắp đặt free wifi marketing,...

**Comment by doainguyen1997** [comment]
Đặt đồ ăn qua mạng --> OK không tồi, nhưng phần liên kết giữa các quán bình dân lại với nhau thì sao sao ấy, vì các quán bán những đồ ăn, nước uống khác nhau, luôn muốn mình có lợi hơn nên việc liên kết lại cần có một bộ phận đứng ra quản lí, chia doanh thu và tạo quảng cáo với thương hiệu duy nhất đến khách hàng mới có thể tạo sức hút đối với các hộ kinh doanh vừa và nhỏ
