### ISSUE TITLE
Phần Mềm Quản Lí Bãi Đỗ Phương Tiện Cá Nhân

### ISSUE THREAD

**Issue by doainguyen1997** [CNPMGroup12-2017/CNPM#4]
Như mọi người đều biết, ủy ban nhân dân thành phố Hà Nội đã ra công văn chính thức đến năm 2030, Hà Nội sẽ tiến tới cấm các phương tiện cá nhân lưu thông trong nội thành, nhằm giảm ùn tắc giao thông và ô nhiễm môi trường. Theo đó, từ nay đến năm 2025, Hà Nội sẽ quy hoạch mạng lưới giao thông công cộng và các điểm trông giữ xe của người dân từ ngoại thành và các tỉnh lân cận.
Chính vì vậy, mình có ý tưởng xây dựng một ứng dụng phần mềm trên thiết bị di động, sử dụng google map, cho phép người dân có thể biết được các điểm trông giữ xe (tổng số chỗ, số chỗ còn trống,..), khoảng cách đến các điểm đó đến các bến xe bus hay ga tàu điện, cho phép đăng kí gửi xe online để giữ slot. Từ đó, người dân có thể lựa chọn các điểm trông giữ xe phù hợp.
Hiện nay theo thống kê thì 10 người sống ở Hà Nội thì có 6 người đi xe máy, 2 người đi ô tô, 1 người đi phương tiện giao thông công cộng và người còn lại đi phương tiện khác (báo viết vậy). Chưa kể dân ngoại thành đi xe máy rất nhiều, vì vậy, mình nghĩ ý tưởng này cũng rất thiết thực

**Comment by NguyenThanhChung147** [comment]
Ok ý tưởng này tốt nhưng Việt Nam đất trật tắc đường ý thức kém lắm đấy còn chưa kể cơ sở hạ tầng thiết bị phục vụ bị bóc ruột hết ngay từ gói thầu thì chịu

**Comment by doainguyen1997** [comment]
Tất nhiên, t nghĩ việc quy hoạch không phải đơn giản, và với Việt Nam thì ý tưởng mãi mãi chỉ nằm trên giấy mà thôi
