### ISSUE TITLE
Phần Mềm Cảnh Báo Bão

### ISSUE THREAD

**Issue by doainguyen1997** [CNPMGroup12-2017/CNPM#5]
Mỗi một cơn bão hay áp thấp nhiệt đới đổ bộ vào nước ta đều để lại những hậu quả vô cùng to lớn. Điển hình là miền trung khi cơn bão số 10 có sức càn quét khôn lường đã cuốn bay mọi thứ. Mặc dù đã có thông tin về cơn bão, song thông tin đối với bà con vùng lũ vẫn rất mờ nhạt nên công tác chủ động phòng chống bão chỉ mang tính hình thức, tạm bợ. Và sau đó lại đau lòng khi vẫn có số liệu về số người chết, mất tích, bị thương, tài sản không kịp sơ tán,... 
Thông tin về bão được dự đoán về rất sớm, nhưng không được cập nhật liên tục và không thống nhất giữa  các bản tin. Mình đề xuất làm một app cảnh báo bão, cả trên thiết bị di động hay máy tính đều sử dụng được, có sử dụng google map với màn hình có màu sắc theo các cấp độ nguy hiểm của bão (đỏ, xanh, vàng), có các bản tin tức được cập nhật liên tục, mới nhất, thông tin thời tiết từ vị trí định vị khách hàng, các vùng rốn bão, đường đi và sức mạnh của bão,...
Ngoài ra, khi không có bão thì app vẫn được sử dụng như một công cụ theo dõi thời tiết từ vị trí của khách hàng.

**Comment by NguyenThanhChung147** [comment]
Đoài ơi ông coment các cái trên như cái coment của t chứ sao lại tạp ý tưởng mới @@

**Comment by NguyenThanhChung147** [comment]
Ý tưởng này tôi sợ mình không có dữ liệu để thống kê thôi. Mà dữ liệu đắt đỏ lắm bên Nhật bán lại cho Việt Nam giá 10000 $ một cái ảnh vệ tinh đấy thầy dạy môn khoa học trái đất và sự sống bảo rồi mà

**Comment by doainguyen1997** [comment]
Thì mình có thể tổng hợp dữ liệu từ trung tâm khí tượng và thủy văn trung ương khi họ vừa công bố, hoặc liên kết ngầm với bên họ
